version: '3.4'

services:

  tourism-api:
    image: ${DOCKER_REGISTRY-}tourismapi
    build:
      context: .
      dockerfile: Tourism-Api/Dockerfile

  sqldata:
    image:  mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=luboy#2022
      - ACCEPT_EULA=Y
    volumes:
      - c:\mssql:/var/opt/mssql/data
    ports:
      - "8080-8081"


  
        
